# Thank you for supporting KTAR!
# Your sponsorship helps us maintain and improve this project

github: [felipemacedo1]
# ko_fi: add_your_username_here
# patreon: add_your_username_here
# buy_me_a_coffee: add_your_username_here
